baseURL = 'https://beim.github.io/'
languageCode = 'en-us'
title = 'beim.github.io'
theme = "paper"

# https://themes.gohugo.io/themes/hugo-paper/
[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  github = 'beim'


  # misc
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true           